#!/bin/sh

if [ -z "$1" ];then
    echo "\nValid arguments are start-dev, stop-dev, start-prod and stop-prod\n"

    elif [ "$1" = "start-dev" ]; then
        docker compose -f docker-compose.dev.yml up

    elif [ "$1" = "start-prod" ]; then 
        docker compose -f docker-compose.yml up

    elif [ "$1" = "stop-dev" ]; then 
        docker compose -f docker-compose.dev.yml down

    elif [ "$1" = "stop-prod" ]; then 
        docker compose -f docker-compose.yml down

    else 
        echo "\nValid arguments are start-dev, stop-dev, start-prod and stop-prod\n"
fi
